dist: bionic
language: ruby
addons:
  apt:
    packages:
      - libdigest-sha-perl
      - shunit2
notifications:
  email: false
sudo: false
script:
  - env -i PATH="$PATH" tests/test
  - shasum --algorithm 1 --check --strict ./SHA1SUM
