#!/bin/bash

urlencode() {
  echo "$1" | curl -Gso /dev/null -w %{url_effective} --data-urlencode @- "" | cut -c 3- | sed -e 's/%0A//'
}

repoUrlMatcher="^(https|git)(:\/\/|@)([^\/:]+)[\/:]([^\/:]+)\/(.+).git$"

gurl=$(git config --get remote.origin.url)
if [[ $gurl =~ $repoUrlMatcher ]]; then
    _REPO_OWNER=${BASH_REMATCH[4]}
    _REPO_NAME=${BASH_REMATCH[5]}
fi

_SHA=$(git rev-parse HEAD)
_BRANCH=$(git rev-parse --abbrev-ref HEAD)
_BRANCH=$(urlencode $_BRANCH)
if [ "$_BRANCH" = "HEAD" ];
then
  _BRANCH=""
fi

export PATH=$PWD:$PATH

function reset () {
    rm -rf temp bower .bowerrc codecov.yml tests/.codecov.yml
    # git commit --amend -m 'nothing special'
    mkdir -p temp
    mkdir -p ~/Library/Developer/Xcode/DerivedData
    . tests/env
    echo '{"file.txt":[null, 1, 0]}' > temp/coverage.json
    echo '{"another.txt":[null, 1, 0]}' > temp/coverage.xml
    touch temp/file.rb
    echo 'blank' > temp/not-file.json
}

function assertDiff () {
    diff <(erb "$2") <(echo "$1")
    assertTrue 'Expected output differs.' $?
}

function assertContains () {
    python -c "import sys; assert sys.argv[2] in sys.argv[1]" "$1" "$2" 2>/dev/null
    assertTrue ">>>>>> $1 <<<<<< does not contain $2" $?
}

function assertNotContains () {
    python -c "import sys; assert sys.argv[2] not in sys.argv[1]" "$1" "$2" 2>/dev/null
    assertTrue ">>>>>> $1 <<<<<< does contain $2" $?
}

function test_help () {
    reset
    assertContains "$(./codecov -h)" "Global report uploading tool for Codecov"
    assertNotContains "$(./codecov -h)" "Searching for coverage reports"
}

function test_fixes () {
    reset
    res=$(./codecov -d)
    while read l; do
      assertContains "$res" "$l"
    done <ignores/results.txt
}

# ------------
# Test Options
# ------------
function test_url_opt () {
    reset
    res=$(./codecov -d -u http://example.com | grep "http://example.com/")
    diff <(echo "http://example.com/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=&build_url=&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

function test_url_env () {
    reset
    res=$(CODECOV_URL="http://other.com" ./codecov -d | grep "http://other.com/")
    diff <(echo "http://other.com/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=&build_url=&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

function test_flags_opt () {
    reset
    res=$(./codecov -d -F f1 -F f2 | grep "https://codecov.io/")
    diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=&build_url=&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=&flags=f1,f2&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

# function test_yaml_location () {
#     reset
#     echo 'codecov:
#   url: http://other.com
#   token: abc123
#   slug: owner/repo
# ' > codecov.yml
#     res=$(./codecov -d | grep "http://other.com/")
#     diff <(echo "http://other.com/upload/v4?package=bash-tbd&token=abc123&branch=$_BRANCH&commit=$_SHA&build=&build_url=&tag=&slug=owner/repo&yaml=codecov.yml&service=&flags=&pr=&job=") <(echo "$res")
#     assertTrue 'Expected output differs.' $?
# }
#
# function test_yaml_location_2 () {
#     reset
#     echo 'codecov:
#   token: uuid
# ' > tests/.codecov.yml
#     res=$(./codecov -d | grep "https://codecov.io/")
#     diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=uuid&branch=$_BRANCH&commit=$_SHA&build=&build_url=&tag=&slug=codecov%2Fcodecov-bash&yaml=tests%2F.codecov.yml&service=&flags=&pr=&job=") <(echo "$res")
#     assertTrue 'Expected output differs.' $?
# }

function test_build_arg () {
    reset
    res=$(./codecov -d -b 1.6 | grep "https://codecov.io/")
    diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=1.6&build_url=&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

# function test_changes_merge_commit () {
#     reset
#     git commit --amend -m 'Merge 5d4123bcb99dd1bc9b5ae8b4271b39dbe4c3928b into 2f85ca252d69d6c52484f0c4b2e8500498228398'
#     res=$(./codecov -d -b 1.6 | grep "https://codecov.io/")
#     diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=5d4123bcb99dd1bc9b5ae8b4271b39dbe4c3928b&build=&build_url=&tag=&slug=codecov%2Fcodecov-bash&service=&flags=&pr=&job=") <(echo "$res")
#     assertTrue 'Expected output differs.' $?
# }

function test_bowerrc_empty () {
    reset
    mkdir bower_components
    touch bower_components/file.md
    res=$(./codecov -d | grep "bower_components/file.md")
    rm -rf bower_components
    assertEquals '' "$res"
}

function test_bowerrc () {
    reset
    echo '{"directory": "bower/"}' > .bowerrc
    mkdir bower
    touch bower/file.md
    res=$(./codecov -d | grep "bower/file.md")
    rm -rf bower
    rm .bowerrc
    assertEquals '' "$res"
}

function test_bowerrc_2 () {
    reset
    echo '{    "directory":

  "bower/" }' > .bowerrc
    mkdir bower
    touch bower/file.md
    res=$(./codecov -d | grep "bower/file.md")
    rm -rf bower
    rm .bowerrc
    assertEquals '' "$res"
}

function test_env_opt () {
    reset

    res="$(BUILD_ID="apples" ./codecov -de BUILD_ID)"
    assertContains "$res" 'BUILD_ID=apples'

    res="$(COMMIT="abc" BUILD_ID="apples" ./codecov -de BUILD_ID,COMMIT)"
    assertContains "$res" 'BUILD_ID=apples'
    assertContains "$res" 'COMMIT=abc'
}

function test_env_env () {
    reset
    res="$(CODECOV_ENV="BUILD_ID" BUILD_ID="apples" ./codecov -d)"
    assertContains "$res" 'BUILD_ID=apples'

    res="$(CODECOV_ENV="BUILD_ID,COMMIT" COMMIT="abc" BUILD_ID="apples" ./codecov -d)"
    assertContains "$res" 'BUILD_ID=apples'
    assertContains "$res" 'COMMIT=abc'
}

function test_slug_opt () {
    reset
    res=$(./codecov -dr myowner/myrepo | grep "https://codecov.io/")
    diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=&build_url=&name=&tag=&slug=myowner%2Fmyrepo&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

function test_slug_env () {
    reset
    export CODECOV_SLUG="myowner/myrepo"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=&build_url=&name=&tag=&slug=myowner%2Fmyrepo&service=&flags=&pr=&job="
}

function test_gcov () {
    reset
    ./codecov -d -X gcov -K | grep '**> gcov disable'
    assertTrue 'gcov was disabled' $?
}

function test_file_opt () {
    reset
    assertContains "$(./codecov -df temp/coverage.json -K)" "+ temp/coverage.json bytes=2"
}

function test_token_opt () {
    reset
    token="38cd42da-4df4-4760-a998-4ebeca536904"
    res=$(./codecov -d -t "$token" | grep "https://codecov.io/")
    diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=$token&branch=$_BRANCH&commit=$_SHA&build=&build_url=&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

function test_token_env () {
    reset
    res=$(CODECOV_TOKEN="38cd42da-4df4-4760-a998-4ebeca536904" ./codecov -d | grep "https://codecov.io/")
    diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=$token&branch=$_BRANCH&commit=$_SHA&build=&build_url=&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

 function test_upload () {
     reset
     export CI="true"
     export TRAVIS_JOB_ID="33116958"
     export TRAVIS="true"
     export TRAVIS_BRANCH="master"
     export TRAVIS_COMMIT="c739768fcac68144a3a6d82305b9c4106934d31a"
     export TRAVIS_REPO_SLUG='codecov/ci-repo'
     export TRAVIS_JOB_ID="33116958"
     export TRAVIS_PULL_REQUEST="false"
     export TRAVIS_JOB_NUMBER="4.1"
     res=$(./codecov)
     assertContains "$res" "View reports at"
     assertContains "$res" "https://codecov.io/github/codecov/ci-repo/commit/c739768fcac68144a3a6d82305b9c4106934d31a"
 }

# -----------------
# Test CI Companies
# -----------------
function assertURL () {
    url=$(./codecov -d | grep 'https://codecov.io/')
    diff <(echo "$1") <(echo "$url")
    assertTrue 'Expected output differs.' $?
}

function test_travis () {
    reset
    export CI="true"
    export TRAVIS_JOB_ID="33116958"
    export TRAVIS="true"
    export TRAVIS_BRANCH="master"
    export TRAVIS_COMMIT="c739768fcac68144a3a6d82305b9c4106934d31a"
    export TRAVIS_REPO_SLUG='codecov/ci-repo'
    export TRAVIS_JOB_ID="33116958"
    export TRAVIS_PULL_REQUEST="false"
    export TRAVIS_JOB_NUMBER="4.1"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=master&commit=c739768fcac68144a3a6d82305b9c4106934d31a&build=4.1&build_url=&name=&tag=&slug=codecov%2Fci-repo&service=travis&flags=&pr=false&job=33116958"
}

function test_jenkins (){
    reset
    export JENKINS_URL="something"
    export GIT_BRANCH="develop"
    export GIT_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    export BUILD_NUMBER="15.1"
    export BUILD_URL="http://endpoint"
    export WORKSPACE="."
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=15.1&build_url=http%3A%2F%2Fendpoint&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=jenkins&flags=&pr=&job="
}

function test_jenkins_blue (){
    reset
    export JENKINS_URL="something"
    export BRANCH_NAME="develop"
    export CHANGE_ID="1"
    export GIT_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    export BUILD_NUMBER="15.1"
    export BUILD_URL="http://endpoint"
    export WORKSPACE="."
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=15.1&build_url=http%3A%2F%2Fendpoint&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=jenkins&flags=&pr=1&job="
}

function test_bitrise (){
    reset
    export CI="true"
    export BITRISE_IO="true"
    export BITRISE_GIT_BRANCH="develop"
    export GIT_CLONE_COMMIT_HASH="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    export BITRISE_BUILD_NUMBER="15.1"
    export BITRISE_PULL_REQUEST="1"
    export BITRISE_BUILD_URL="http://endpoint"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=15.1&build_url=http%3A%2F%2Fendpoint&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=bitrise&flags=&pr=1&job="
}

function test_jenkins_vars (){
    reset
    export JENKINS_URL="something"
    export ghprbSourceBranch="develop"
    export ghprbActualCommit="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    export BUILD_NUMBER="15.1"
    export BUILD_URL="http://endpoint"
    export WORKSPACE="."
    export ghprbPullId="5"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=15.1&build_url=http%3A%2F%2Fendpoint&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=jenkins&flags=&pr=5&job="
}

function test_codeship (){
    reset
    export CI="true"
    export CI_NAME="codeship"
    export CI_BRANCH="develop"
    export CI_BUILD_NUMBER="12.1"
    export CI_BUILD_URL="http://endpoint"
    export CI_COMMIT_ID="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=12.1&build_url=http%3A%2F%2Fendpoint&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=codeship&flags=&pr=&job="
}

function test_semaphore (){
    reset
    export CI="true"
    export SEMAPHORE="true"
    export SEMAPHORE_REPO_SLUG="myowner/myrepo"
    export BRANCH_NAME="develop"
    export SEMAPHORE_BUILD_NUMBER="8"
    export SEMAPHORE_CURRENT_THREAD="2"
    export REVISION="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=8&build_url=&name=&tag=&slug=myowner%2Fmyrepo&service=semaphore&flags=&pr=&job=2"
}

function test_buildkite (){
    reset
    export CI="true"
    export BUILDKITE="true"
    export BUILDKITE_PROJECT_SLUG="myowner/myrepo"
    export BUILDKITE_BRANCH="develop"
    export BUILDKITE_BUILD_NUMBER="8"
    export BUILDKITE_JOB_ID="1"
    export BUILDKITE_BUILD_URL="http://buildkite"
    export BUILDKITE_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=8&build_url=http%3A%2F%2Fbuildkite&name=&tag=&slug=myowner%2Fmyrepo&service=buildkite&flags=&pr=&job=1"
}

function test_solano (){
    reset
    export TDDIUM="true"
    export TDDIUM_CURRENT_BRANCH="develop"
    export TDDIUM_TID="12311"
    export TDDIUM_PR_ID="false"
    export TDDIUM_CURRENT_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=12311&build_url=&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=solano&flags=&pr=false&job="
}

function test_drone (){
    reset
    export CI="drone"
    export DRONE_BRANCH="develop"
    export DRONE_BUILD_NUMBER="7.5"
    export DRONE_BUILD_LINK="http://drone"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=$_SHA&build=7.5&build_url=http%3A%2F%2Fdrone&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=drone.io&flags=&pr=&job="
}

function test_appveyor (){
    reset
    export CI="True"
    export APPVEYOR="True"
    export APPVEYOR_REPO_NAME="myowner/myrepo"
    export APPVEYOR_REPO_BRANCH="develop"
    export APPVEYOR_BUILD_VERSION="1.2.3"
    export APPVEYOR_PULL_REQUEST_NUMBER="1"
    export APPVEYOR_ACCOUNT_NAME="a"
    export APPVEYOR_PROJECT_SLUG="b"
    export APPVEYOR_JOB_ID="9r2qufuu8"
    export APPVEYOR_REPO_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=9r2qufuu8&build_url=&name=&tag=&slug=myowner%2Fmyrepo&service=appveyor&flags=&pr=1&job=a%2Fb%2F1.2.3"
}

function test_wercker (){
    reset
    export CI="true"
    export WERCKER_GIT_BRANCH="develop"
    export WERCKER_MAIN_PIPELINE_STARTED="12311"
    export WERCKER_GIT_OWNER="myowner"
    export WERCKER_GIT_REPOSITORY="myrepo"
    export WERCKER_GIT_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=12311&build_url=&name=&tag=&slug=myowner%2Fmyrepo&service=wercker&flags=&pr=&job="
}

function test_magnum (){
    reset
    export CI="true"
    export MAGNUM="true"
    export CI_BRANCH="develop"
    export CI_BUILD_NUMBER="12311"
    export CI_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=12311&build_url=&name=&tag=&slug=$_REPO_OWNER%2F$_REPO_NAME&service=magnum&flags=&pr=&job="
}

function test_shippable (){
    reset
    export SHIPPABLE="true"
    export BRANCH="develop"
    export BUILD_NUMBER="1.2"
    export REPO_FULL_NAME="myowner/myrepo"
    export BUILD_URL="http://shippable"
    export PULL_REQUEST="2"
    export COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=1.2&build_url=http%3A%2F%2Fshippable&name=&tag=&slug=myowner%2Fmyrepo&service=shippable&flags=&pr=2&job="
}

function test_prow_presubmit (){
    reset
    export PROW_JOB_ID=91c3ff58-3a97-11e9-a034-0a58ac105a97
	export BUILD_ID=1
	export JOB_TYPE=postsubmit
	export JOB_NAME=prowpresubmit
	export PULL_BASE_REF=master
	export PULL_BASE_SHA=40634e665221384257bd8dd9129145c0fe537916
	export PULL_NUMBER=1
	export PULL_PULL_SHA=82eb60d5e6796a330b8b61f9a9d4ae68c108a94a
	export REPO_NAME=myrepo
	export REPO_OWNER=owner
	export CI_BUILD_URL="https://prow"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=master&commit=40634e665221384257bd8dd9129145c0fe537916&build=1&build_url=https%3A%2F%2Fprow&name=&tag=&slug=owner%2Fmyrepo&service=prow&flags=&pr=1&job=91c3ff58-3a97-11e9-a034-0a58ac105a97"
}

function test_prow_postsubmit (){
    reset
    export PROW_JOB_ID=91c3ff58-3a97-11e9-a034-0a58ac105a97
	export BUILD_ID=1
	export JOB_TYPE=postsubmit
	export JOB_NAME=prowpostsubmit
	export PULL_BASE_REF=master
	export PULL_BASE_SHA=40634e665221384257bd8dd9129145c0fe537916
	export REPO_NAME=myrepo
	export REPO_OWNER=owner
	export CI_BUILD_URL="https://prow"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=master&commit=40634e665221384257bd8dd9129145c0fe537916&build=1&build_url=https%3A%2F%2Fprow&name=&tag=&slug=owner%2Fmyrepo&service=prow&flags=&pr=&job=91c3ff58-3a97-11e9-a034-0a58ac105a97"
}

# Call and Run all Tests
. "shunit2-2.1.6/src/shunit2"
