#!/bin/bash

export _SHA=$(git rev-parse HEAD)
export _BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$_BRANCH" = "HEAD" ];
then
  _BRANCH=""
fi

export PATH=$PWD:$PATH

function reset () {
    rm -rf temp bower .bowerrc codecov.yml tests/.codecov.yml
    # git commit --amend -m 'nothing special'
    mkdir -p temp
    mkdir -p ~/Library/Developer/Xcode/DerivedData
    . tests/env
    echo '{"file.txt":[null, 1, 0]}' > temp/coverage.json
    echo '{"another.txt":[null, 1, 0]}' > temp/coverage.xml
    touch temp/file.rb
    echo 'blank' > temp/not-file.json
}

function assertDiff () {
    diff <(erb "$2") <(echo "$1")
    assertTrue 'Expected output differs.' $?
}

function assertContains () {
    if [ "$(echo "$1" | grep "$2")" = "" ];
    then
        echo "$1 does not contain $2"
    fi
}

function test_help () {
    reset
    assertContains "$(./codecov -h)" "Upload reports to Codecov"
}

# ------------
# Test Options
# ------------
function test_url_opt () {
    reset
    res=$(./codecov -d -u http://example.com | grep "http://example.com/")
    diff <(echo "http://example.com/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=&build_url=&tag=&slug=&yaml=&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

function test_url_env () {
    reset
    res=$(CODECOV_URL="http://other.com" ./codecov -d | grep "http://other.com/")
    diff <(echo "http://other.com/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=&build_url=&tag=&slug=&yaml=&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

function test_flags_opt () {
    reset
    res=$(./codecov -d -F f1 -F f2 | grep "https://codecov.io/")
    diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=&build_url=&tag=&slug=&yaml=&service=&flags=f1,f2&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

# function test_yaml_location () {
#     reset
#     echo 'codecov:
#   url: http://other.com
#   token: abc123
#   slug: owner/repo
# ' > codecov.yml
#     res=$(./codecov -d | grep "http://other.com/")
#     diff <(echo "http://other.com/upload/v4?package=bash-tbd&token=abc123&branch=$_BRANCH&commit=$_SHA&build=&build_url=&tag=&slug=owner/repo&yaml=codecov.yml&service=&flags=&pr=&job=") <(echo "$res")
#     assertTrue 'Expected output differs.' $?
# }
#
# function test_yaml_location_2 () {
#     reset
#     echo 'codecov:
#   token: uuid
# ' > tests/.codecov.yml
#     res=$(./codecov -d | grep "https://codecov.io/")
#     diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=uuid&branch=$_BRANCH&commit=$_SHA&build=&build_url=&tag=&slug=&yaml=tests%2F.codecov.yml&service=&flags=&pr=&job=") <(echo "$res")
#     assertTrue 'Expected output differs.' $?
# }

function test_build_arg () {
    reset
    res=$(./codecov -d -b 1.6 | grep "https://codecov.io/")
    diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=1.6&build_url=&tag=&slug=&yaml=&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

# function test_changes_merge_commit () {
#     reset
#     git commit --amend -m 'Merge 5d4123bcb99dd1bc9b5ae8b4271b39dbe4c3928b into 2f85ca252d69d6c52484f0c4b2e8500498228398'
#     res=$(./codecov -d -b 1.6 | grep "https://codecov.io/")
#     diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=5d4123bcb99dd1bc9b5ae8b4271b39dbe4c3928b&build=&build_url=&tag=&slug=&yaml=&service=&flags=&pr=&job=") <(echo "$res")
#     assertTrue 'Expected output differs.' $?
# }

function test_bowerrc_empty () {
    reset
    mkdir bower_components
    touch bower_components/file.md
    res=$(./codecov -d | grep "bower_components/file.md")
    rm -rf bower_components
    assertEquals '' "$res"
}

function test_bowerrc () {
    reset
    echo '{"directory": "bower/"}' > .bowerrc
    mkdir bower
    touch bower/file.md
    res=$(./codecov -d | grep "bower/file.md")
    rm -rf bower
    rm .bowerrc
    assertEquals '' "$res"
}

function test_bowerrc_2 () {
    reset
    echo '{    "directory":

  "bower/" }' > .bowerrc
    mkdir bower
    touch bower/file.md
    res=$(./codecov -d | grep "bower/file.md")
    rm -rf bower
    rm .bowerrc
    assertEquals '' "$res"
}

function test_env_opt () {
    reset

    res="$(BUILD_ID="apples" ./codecov -de BUILD_ID)"
    assertContains "$res" 'BUILD_ID=apples'

    res="$(COMMIT="abc" BUILD_ID="apples" ./codecov -de BUILD_ID,COMMIT)"
    assertContains "$res" 'BUILD_ID=apples'
    assertContains "$res" 'COMMIT=abc'
}

function test_env_env () {
    reset
    res="$(CODECOV_ENV="BUILD_ID" BUILD_ID="apples" ./codecov -d)"
    assertContains "$res" 'BUILD_ID=apples'

    res="$(CODECOV_ENV="BUILD_ID,COMMIT" COMMIT="abc" BUILD_ID="apples" ./codecov -d)"
    assertContains "$res" 'BUILD_ID=apples'
    assertContains "$res" 'COMMIT=abc'
}

function test_slug_opt () {
    reset
    res=$(./codecov -dr myowner/myrepo | grep "https://codecov.io/")
    diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=&build_url=&tag=&slug=myowner/myrepo&yaml=&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

function test_slug_env () {
    reset
    export CODECOV_SLUG="myowner/myrepo"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=$_BRANCH&commit=$_SHA&build=&build_url=&tag=&slug=myowner/myrepo&yaml=&service=&flags=&pr=&job="
}

function test_gcov () {
    reset
    ./codecov -d -X gcov -K | grep '**> gcov disable'
    assertTrue 'gcov was disabled' $?
}

function test_file_opt () {
    reset
    assertContains "$(./codecov -df temp/coverage.json -K)" "+ temp/coverage.json bytes=25"
}

function test_token_opt () {
    reset
    token="38cd42da-4df4-4760-a998-4ebeca536904"
    res=$(./codecov -d -t "$token" | grep "https://codecov.io/")
    diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=$token&branch=$_BRANCH&commit=$_SHA&build=&build_url=&tag=&slug=&yaml=&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

function test_token_env () {
    reset
    res=$(CODECOV_TOKEN="38cd42da-4df4-4760-a998-4ebeca536904" ./codecov -d | grep "https://codecov.io/")
    diff <(echo "https://codecov.io/upload/v4?package=bash-tbd&token=$token&branch=$_BRANCH&commit=$_SHA&build=&build_url=&tag=&slug=&yaml=&service=&flags=&pr=&job=") <(echo "$res")
    assertTrue 'Expected output differs.' $?
}

function test_upload () {
    reset
    export CI="true"
    export TRAVIS_JOB_ID="33116958"
    export TRAVIS="true"
    export TRAVIS_BRANCH="master"
    export TRAVIS_COMMIT="c739768fcac68144a3a6d82305b9c4106934d31a"
    export TRAVIS_REPO_SLUG='codecov/ci-repo'
    export TRAVIS_JOB_ID="33116958"
    export TRAVIS_PULL_REQUEST="false"
    export TRAVIS_JOB_NUMBER="4.1"
    res=$(./codecov | grep "http://codecov.io")
    assertContains "$res" "Reports queued to"
    assertContains "$res" "http://codecov.io/github/codecov/ci-repo?ref=c739768fcac68144a3a6d82305b9c4106934d31a"
}

# -----------------
# Test CI Companies
# -----------------
function assertURL () {
    url=$(./codecov -d | grep 'https://codecov.io/')
    diff <(echo "$1") <(echo "$url")
    assertTrue 'Expected output differs.' $?
}

function test_travis () {
    reset
    export CI="true"
    export TRAVIS_JOB_ID="33116958"
    export TRAVIS="true"
    export TRAVIS_BRANCH="master"
    export TRAVIS_COMMIT="c739768fcac68144a3a6d82305b9c4106934d31a"
    export TRAVIS_REPO_SLUG='codecov/ci-repo'
    export TRAVIS_JOB_ID="33116958"
    export TRAVIS_PULL_REQUEST="false"
    export TRAVIS_JOB_NUMBER="4.1"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=master&commit=c739768fcac68144a3a6d82305b9c4106934d31a&build=4.1&build_url=&tag=&slug=codecov/ci-repo&yaml=&service=travis&flags=&pr=false&job=33116958"
}

function test_jenkins (){
    reset
    export JENKINS_URL="something"
    export GIT_BRANCH="develop"
    export GIT_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    export BUILD_NUMBER="15.1"
    export BUILD_URL="http://endpoint"
    export WORKSPACE="."
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=15.1&build_url=http%3A%2F%2Fendpoint&tag=&slug=&yaml=&service=jenkins&flags=&pr=&job="
}

function test_bitrise (){
    reset
    export CI="true"
    export BITRISE_IO="true"
    export BITRISE_GIT_BRANCH="develop"
    export BITRISE_GIT_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    export BITRISE_BUILD_NUMBER="15.1"
    export BITRISE_PULL_REQUEST="1"
    export BITRISE_BUILD_URL="http://endpoint"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=15.1&build_url=http%3A%2F%2Fendpoint&tag=&slug=&yaml=&service=bitrise&flags=&pr=1&job="
}

function test_jenkins_vars (){
    reset
    export JENKINS_URL="something"
    export ghprbSourceBranch="develop"
    export ghprbActualCommit="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    export BUILD_NUMBER="15.1"
    export BUILD_URL="http://endpoint"
    export WORKSPACE="."
    export ghprbPullId="5"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=15.1&build_url=http%3A%2F%2Fendpoint&tag=&slug=&yaml=&service=jenkins&flags=&pr=5&job="
}

function test_codeship (){
    reset
    export CI="true"
    export CI_NAME="codeship"
    export CI_BRANCH="develop"
    export CI_BUILD_NUMBER="12.1"
    export CI_BUILD_URL="http://endpoint"
    export CI_COMMIT_ID="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=12.1&build_url=http%3A%2F%2Fendpoint&tag=&slug=&yaml=&service=codeship&flags=&pr=&job="
}


function test_semaphore (){
    reset
    export CI="true"
    export SEMAPHORE="true"
    export SEMAPHORE_REPO_SLUG="myowner/myrepo"
    export BRANCH_NAME="develop"
    export SEMAPHORE_BUILD_NUMBER="8"
    export SEMAPHORE_CURRENT_THREAD="2"
    export REVISION="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=8.2&build_url=&tag=&slug=myowner/myrepo&yaml=&service=semaphore&flags=&pr=&job="
}

function test_buildkite (){
    reset
    export CI="true"
    export BUILDKITE="true"
    export BUILDKITE_PROJECT_SLUG="myowner/myrepo"
    export BUILDKITE_BRANCH="develop"
    export BUILDKITE_BUILD_NUMBER="8"
    export BUILDKITE_JOB_ID="1"
    export BUILDKITE_BUILD_URL="http://buildkite"
    export BUILDKITE_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=8.1&build_url=http%3A%2F%2Fbuildkite&tag=&slug=myowner/myrepo&yaml=&service=buildkite&flags=&pr=&job="
}

function test_drone (){
    reset
    export CI="true"
    export DRONE="true"
    export DRONE_BRANCH="develop"
    export DRONE_BUILD_NUMBER="7.5"
    export DRONE_BUILD_URL="http://drone"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=$_SHA&build=7.5&build_url=http%3A%2F%2Fdrone&tag=&slug=&yaml=&service=drone.io&flags=&pr=&job="
}

function test_appveyor (){
    reset
    export CI="True"
    export APPVEYOR="True"
    export APPVEYOR_REPO_NAME="myowner/myrepo"
    export APPVEYOR_REPO_BRANCH="develop"
    export APPVEYOR_BUILD_VERSION="1.2.3"
    export APPVEYOR_PULL_REQUEST_NUMBER="1"
    export APPVEYOR_ACCOUNT_NAME="a"
    export APPVEYOR_PROJECT_SLUG="b"
    export APPVEYOR_JOB_ID="9r2qufuu8"
    export APPVEYOR_REPO_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=9r2qufuu8&build_url=&tag=&slug=myowner/myrepo&yaml=&service=appveyor&flags=&pr=1&job=a%2Fb%2F1.2.3"
}

function test_wercker (){
    reset
    export CI="true"
    export WERCKER_GIT_BRANCH="develop"
    export WERCKER_MAIN_PIPELINE_STARTED="12311"
    export WERCKER_GIT_OWNER="myowner"
    export WERCKER_GIT_REPOSITORY="myrepo"
    export WERCKER_GIT_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=12311&build_url=&tag=&slug=myowner/myrepo&yaml=&service=wercker&flags=&pr=&job="
}

function test_magnum (){
    reset
    export CI="true"
    export MAGNUM="true"
    export CI_BRANCH="develop"
    export CI_BUILD_NUMBER="12311"
    export CI_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=12311&build_url=&tag=&slug=&yaml=&service=magnum&flags=&pr=&job="
}

function test_snap_ci (){
    reset
    export CI="true"
    export SNAP_CI="true"
    export SNAP_BRANCH="develop"
    export SNAP_PIPELINE_COUNTER="12311"
    export SNAP_PULL_REQUEST_NUMBER="1"
    export SNAP_COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=12311&build_url=&tag=&slug=&yaml=&service=snap&flags=&pr=1&job="
}

function test_shippable (){
    reset
    export SHIPPABLE="true"
    export BRANCH="develop"
    export BUILD_NUMBER="1.2"
    export REPO_FULL_NAME="myowner/myrepo"
    export BUILD_URL="http://shippable"
    export PULL_REQUEST="2"
    export COMMIT="180c0d097354fc1a451da8a3be5aba255f2ffd9f"
    assertURL "https://codecov.io/upload/v4?package=bash-tbd&token=&branch=develop&commit=180c0d097354fc1a451da8a3be5aba255f2ffd9f&build=1.2&build_url=http%3A%2F%2Fshippable&tag=&slug=myowner/myrepo&yaml=&service=shippable&flags=&pr=2&job="
}


# Call and Run all Tests
. "shunit2-2.1.6/src/shunit2"
