#!/usr/bin/env bash

for i in 1 256 512; do shasum -a "${i}" codecov > "SHA${i}SUM"; done
for i in 1 256 512; do shasum -a "${i}" env >> "SHA${i}SUM"; done
for i in 1 256 512; do git add "SHA${i}SUM"; done
